name: CI

on: [push]

jobs:
  unit-tests:
    name: Unit Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Build project
        run: cargo build -v
      
      - name: Run unit tests
        run: cargo test -v --lib --no-default-features